# Generated by Django 3.1.1 on 2020-09-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_desc', models.CharField(max_length=200)),
                ('job_contact', models.CharField(max_length=100)),
            ],
        ),
    ]
