# Generated by Django 3.1.1 on 2020-09-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
                ('telephone', models.IntegerField(max_length=40)),
                ('intrested_in', models.CharField(max_length=20)),
                ('have_agreed', models.BooleanField(default=False)),
            ],
        ),
    ]
