# Generated by Django 3.1.1 on 2020-09-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancies',
            name='email',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
