# Generated by Django 3.1.1 on 2020-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_auto_20200913_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiries',
            name='telephone',
            field=models.CharField(max_length=20),
        ),
    ]
