# Generated by Django 3.1.1 on 2020-09-13 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_auto_20200913_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiries',
            name='intrested_in',
        ),
    ]
