# Generated by Django 3.1.1 on 2020-09-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_remove_enquiries_intrested_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiries',
            name='intrested_in',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiries',
            name='telephone',
            field=models.CharField(choices=[('carehome', 'Care Home'), ('daycare', 'Day Care'), ('domiciliarycare', 'Domiciliary Care'), ('livein', 'Live In')], default='carehome', max_length=16),
        ),
    ]
